[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "cyber_record"
version = "0.1.13"
description = "Cyber record offline parse tool"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.8"

authors = [ { name = "daohu527", email = "daohu527@gmail.com" } ]

license = { text = "Apache Software License" }

urls = { "Homepage" = "https://github.com/daohu527/cyber_record", "Bug Tracker" = "https://github.com/daohu527/cyber_record/issues" }

classifiers = [
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: Apache Software License",
	"Operating System :: OS Independent",
]

dependencies = [
	"protobuf>=5.29.0,<6",
]

[project.optional-dependencies]
mcap = [
	"mcap",
]
msgs = [
	"wheelos-msgs>=0.1.5",
]
msg-tools = [
	"numpy",
	"Pillow",
	"python-lzf",
]
dev = [
	"build",
	"setuptools",
	"wheel",
	"pytest",
	"mcap",
	"numpy",
	"Pillow",
	"python-lzf",
	"matplotlib",
	"wheelos-msgs>=0.1.5",
]

[project.scripts]
cyber_record = "cyber_record.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["cyber_record*"]
